on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - "v*"

name: release

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    name: tag release
    # This workflow is only of value to the metal3-io/cluster-api-provider-metal3 repository and
    # would always fail in forks
    if: github.repository == 'metal3-io/cluster-api-provider-metal3'
    runs-on: ubuntu-latest
    steps:
      - name: Export RELEASE_TAG var
        run:  echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Install go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.19'
      - name: Generate release artifacts and notes
        run: |
          make release
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          draft: true
          files: out/*
          body_path: releasenotes/${{ env.RELEASE_TAG }}.md
